server {
    # NGINX listens on port 80 inside the container
    listen 80;
    server_name localhost;

    # Set the root directory
    root /usr/share/nginx/html;
    index index.html;

    # Serve static files (HTML, CSS, JS)
    location / {
        try_files $uri $uri/ /index.html;
    }

    
}